### ISSUE TITLE
Docker Compose doesn't load relocated images, causing airgapped deployments to fail

### ISSUE THREAD

**Issue by bherw** [getporter/docker-compose-mixin#26]
According to https://porter.sh/distribute-bundles/#image-references-after-publishing, "Bundles should not hard-code image references and instead should use the images section and templating so that they are referencing the published location of the image."

However, a simple docker-compose.yaml like the following is hardcoding the image references since the porter templating does not apply to the docker-compose.yaml:
```yaml
services:
  foo:
    image: alpine
    entrypoint: /bin/sh -c 'echo test'
```

This example fails in an airgapped environment even if the alpine image is specified in porter.yaml because this docker-compose.yaml file is copied into the invocation image verbatim. docker-compose just sees the "alpine" reference and tries to look it up on docker.io. The official airgap example, on the other hand, works, because the helm command gets the templated image references in the porter.yaml.

We need a way to get the image references from porter to the docker-compose config, ideally without making it impossible to test the compose file simply in the local environment by running `docker-compose up`.

**Comment by bherw** [comment]
docker-compose does pick up environment variables, so what I'm doing right now is a bit of a hack. I have a script doing the following:
- read the docker-compose to find the list of images it needs by content digest
- rewrite porter.yaml with the image manifest
- add exec statements to porter.yaml which echo the image references from the manifest into a file inside the invocation image's container
- rewrite the compose file to use environment variables
- load that file into docker-compose

It ends up looking something like this:

**porter.yaml**
```yaml
images:
  alpine:
    repository: alpine
    digest: alpine@sha256:abcd...........

install:
  - exec:
    command: /bin/sh -c 'echo SERVICE_FOO_IMAGE={{bundle.images.foo.repository}}@{{bundle.images.foo.digest}} >> /root/porter.env'
  - docker-compose:
    arguments:
      - --env-file
      - /root/porter.env
      - up
      - -d
```

**docker-compose.yaml**
```yaml
services:
  foo:
    image: $SERVICE_FOO_IMAGE
    entrypoint: /bin/sh -c 'echo test'
```

Obviously this isn't ideal, but it does work. Along this line, perhaps the docker-compose mixin could produce a similar environment file from the images.

Another idea could be to modify the docker-compose.yaml file to accept input, perhaps from the environment, as a part of the invocation image build process.

**Comment by vdice** [comment]
Thanks for creating this issue and sharing your current approach @bherw.  It would definitely be nice to add built-in support to this mixin for updating the images in the compose yaml.  As you've mentioned, there are at least a few approaches we could use.  I do like the suggestion of seeing if it can be done at the build stage.

**Comment by sathish-kumar-narayanan** [comment]
The other option would be layering it with another compose yaml. Mixin can create one another compose yaml
`docker-compose.images.yaml` with the list of images referenced in porter.yaml, and supply it as file argument in addition to the provided one

**Comment by carolynvs** [comment]
I can't quite tell if you have a suggested solution or not yet? Here's some context extra context that may be helpful (or not):

* the images map in porter.yaml will support resolving the tag to a digest at buildtime https://github.com/getporter/porter/issues/1357. So if an author does have to add the images used, it's a little less work.
* I'd be up for injecting the mapped images as environment variables, e.g. `PORTER_IMAGES_KEY=relocated-image-with-digest` so something like `PORTER_IMAGES_NGINX=localhost:5000/nginx@sha256:abc123`

**Comment by sathish-kumar-narayanan** [comment]
injecting the mapped images as environment variables sounds like a good idea.

**Comment by sathish-kumar-narayanan** [comment]
Example docker-compose.yaml

```yml
services:
  frontend:
    image: awesome/webapp
    ports:
      - "443:8043"
    networks:
      - front-tier
      - back-tier
    configs:
      - httpd-config
    secrets:
      - server-certificate
```
Then, docker-compose.images.yaml would look like 
```yaml
services:
  frontend:
    image: <registry-url>/<image-name>:@sha
```
Effectively docker-compose.images.yaml will override the images from docker-compose.yaml when executing compose like this `docker-compose -f docker-compose.yaml -f docker-compose.images.yaml` 

https://docs.docker.com/compose/extends/
