### ISSUE TITLE
Make the version configurable at build

### ISSUE THREAD

**Issue by carolynvs** [getporter/docker-compose-mixin#5]
Just like helm has a buildtime config to allow installing a specific version of the client, it would be great if we could do the same thing for docker-compose.

```yaml
mixins:
  - docker-compose:
      clientVersion: 1.25.4
```

EDIT: Changed version -> clientVersion
